### ISSUE TITLE
Support for personal accounts/repositories

### ISSUE THREAD

**Issue by FlorisFeddema** [infro-io/issues#1]
Hi, 

I have installed the app on my github account and connected my gitops repo to the app.
However when I go to infro.io I keep getting redirected to the github page instead of the infro.io ui, so I can not connect my argo instance.

It seems like there is a bug where it does not see that I have connected my github repo already?

**Comment by FlorisFeddema** [comment]
My homelab repository is not part of an organization but on my personal github. If I add an organization the ui works. Could you add support for personal accounts/repositories?

**Comment by colethienes** [comment]
> It seems like there is a bug where it does not see that I have connected my github repo already?

I just didn't add support yet 🙂 It's a confusing user flow, but what's happening is the UI isn't detecting any orgs for the logged in person, and just sending you back to org setup.

> Could you add support for personal accounts/repositories?

Yep. Let me do some investigation and get back, but I don't think it should be a problem.

**Comment by colethienes** [comment]
Added support for personal githubs.

**Comment by FlorisFeddema** [comment]
While I can add my personal github account, it does not seem to work yet. It does not run on my github pull requests. Is there a way to debug this for me? Or could you take a look at it.
I really would love to use this tool because it seems to give so much insight!

**Comment by colethienes** [comment]
Hi there - thanks for letting me know! I see from your logs that there's a bug - addressing now...

**Comment by colethienes** [comment]
Okay try now?

**Comment by FlorisFeddema** [comment]
I have broken setup because I moved to new hardware this weekend. I expect to test it this evening.

**Comment by colethienes** [comment]
Just fyi - from looking at the logs it looks like your repo is not being pulled by any Argo apps in your cluster :)

https://github.com/FlorisFeddema/homelab/pull/750/checks?check_run_id=22047358810

**Comment by FlorisFeddema** [comment]
It is: https://github.com/FlorisFeddema/homelab/blob/main/products/argo-cd/templates/application-feddemadev-homelab.yaml

Might it be that Infro does not work with ssh yet? I use ssh as authentication for my github repo (I don't know why I haven't switched to https since the repo is public anyways).
