### ISSUE TITLE
feature: Use collapsed sections for (large) diffs

### ISSUE THREAD

**Issue by rouke-broersma** [infro-io/issues#3]
Instead of:

homelab > intel-device-operator (no changes)
homelab > kube-prometheus-stack

```
blerp
```
homelab > mealie (no changes)

I would like to see:

homelab > intel-device-operator (no changes)
homelab > kube-prometheus-stack (25 files changed)
<details>

```
blerp
```

</details>

homelab > mealie (no changes)

**Comment by colethienes** [comment]
Yeah I'm of the same mind here. Do you think it would be better to see files changed or lines changed? What about the green/red labeled lines changed like on Github? (e.g. ${\color{green}+32}$/ ${\color{red}-14}$)

**Comment by rouke-broersma** [comment]
Lines changed (added and removed) would also be nice in addition, both combined give you an indication of the scope of the change. If it's preferred to only support one I think I would prefer a file counter.

**Comment by colethienes** [comment]
Added collapsible sections! If the diff is over 30 lines, it collapses by default, otherwise it's open.
